from allennlp_rc.predictors.reading_comprehension import ReadingComprehensionPredictor
from allennlp_rc.predictors.dialog_qa import DialogQAPredictor
from allennlp_rc.predictors.transformer_qa import TransformerQAPredictor
